version: "3.9"

services:
  db:
    image: postgres:15
    container_name: etl_postgres
    environment:
      POSTGRES_DB: etl_censo
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init_schemas.sql:/docker-entrypoint-initdb.d/01_init_schemas.sql

  spark-notebooks:
    build: .
    container_name: etl_notebooks
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: etl_censo
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
      SPARK_APP_NAME: censo_etl
    volumes:
      - ./:/app
    ports:
      - "8888:8888"

  airflow-init:
    image: apache/airflow:2.8.1
    container_name: etl_airflow_init
    depends_on:
      - db
    environment:
      &airflow-common-env
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://etl_user:etl_password@db:5432/etl_censo
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
      _PIP_ADDITIONAL_REQUIREMENTS: 'apache-airflow-providers-postgres'
    user: "50000:0"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./:/app
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin
      "

  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: etl_airflow_webserver
    depends_on:
      - airflow-init
    environment:
      <<: *airflow-common-env
    ports:
      - "8080:8080"
    user: "50000:0"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./:/app
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: etl_airflow_scheduler
    depends_on:
      - airflow-init
    environment:
      <<: *airflow-common-env
    user: "50000:0"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./:/app
    command: scheduler

volumes:
  pgdata: